# Generated by Django 6.0.3 on 2026-08-27 12:52

from allauth.account.models import EmailAddress
from allauth.account.utils import user_email
from django.contrib.auth import get_user_model
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0006_alter_userprofile_managers_alter_userprofile_email"),
    ]

    def upgrade_superuser(apps, schema_editor):
        User = get_user_model()
        superuser = User.objects.get(email="superuser@example.com")
        email, created = EmailAddress.objects.get_or_create(
            user=superuser, email=user_email(superuser)
        )
        email.verified = True
        email.save()

    operations = [migrations.RunPython(upgrade_superuser)]
